#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../lib";

use Rplus::Modern;
use Rplus::DB;

use Mojo::Asset::File;
use JSON;
use Data::Dumper;

$Data::Dumper::Terse = 1;
$Data::Dumper::Quotekeys = 0;

my $dbh = Rplus::DB->new_or_cached->dbh;

if (1) {
    say 'updating db';
    $dbh->do(q{ALTER TABLE public.users ADD COLUMN subordinate int4[1] NOT NULL DEFAULT ARRAY[]::integer[];});


    say 'done';
}

sub read_config {
    my $file_name = shift;

    my $file = Mojo::Asset::File->new(path => $file_name);
    my $config = eval $file->slurp;
    return $config;
}

sub write_config {
    my $config = shift;
    my $file_name = shift;

    open OUTFILE, ">$file_name" or die "Can't open '$file_name':$!";

    print OUTFILE Dumper $config;
}

exit 1;
