#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../lib";

use Rplus::Modern;

use Data::Dumper;
use Rplus::DB;

my $dbh = Rplus::DB->new_or_cached->dbh;

$dbh->do(q{DROP TABLE IF EXISTS "public"."variables";});

if(1){
    $dbh->do(q{CREATE TABLE "public"."variables" (
                                    "id" SERIAL PRIMARY KEY,
	                                "name" VARCHAR NOT NULL,
	                                "value" VARCHAR NOT NULL);}
    );
}
1;
