#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../lib";

use Rplus::Modern;

use Rplus::DB;

my $dbh = Rplus::DB->new_or_cached->dbh;

# Database scruct changes
if (1) {
    # Realty table changes
    $dbh->do(q{ALTER TABLE ONLY realty DROP CONSTRAINT IF EXISTS realty_color_tag_fc;});
    $dbh->do(q{ALTER TABLE public.realty DROP COLUMN IF EXISTS color_tag_id;});
    
    $dbh->do(q{DROP TABLE IF EXISTS public.color_tags});
    $dbh->do(q{DROP TABLE IF EXISTS public.dict_color_tags;});

    $dbh->do(q{
CREATE TABLE public.dict_color_tags (
    id SERIAL,
    name VARCHAR(12) NOT NULL,
    color VARCHAR(6)  NOT NULL,
    border_color VARCHAR(6) DEFAULT 'c8c8c8'::character varying NOT NULL,
    add_date TIMESTAMPTZ(6) DEFAULT now() NOT NULL,
    delete_date TIMESTAMPTZ(6));
    });

    $dbh->do(q{ALTER TABLE public.dict_color_tags ADD PRIMARY KEY (id);});

    $dbh->do(q{COMMENT ON TABLE public.dict_color_tags IS 'словарь цветовых тегов для объектов недвижимости';});
    $dbh->do(q{COMMENT ON COLUMN public.dict_color_tags.name IS 'имя тега для отображения пользователю';});
    $dbh->do(q{COMMENT ON COLUMN public.dict_color_tags.color IS 'цвет тега';});
    $dbh->do(q{COMMENT ON COLUMN public.dict_color_tags.border_color IS 'цвет окантовки тега';});
    $dbh->do(q{COMMENT ON COLUMN public.dict_color_tags.add_date IS 'Дата/время добавления';});
    $dbh->do(q{COMMENT ON COLUMN public.dict_color_tags.delete_date IS 'Дата/время удаления';});

    # Records of color_tags
    $dbh->do(q{INSERT INTO public.dict_color_tags (name, color, border_color) VALUES ('красный', 'fd7b7e', 'd9585c');});
    $dbh->do(q{INSERT INTO public.dict_color_tags (name, color, border_color) VALUES ('оранжевый', 'febc46', 'e99532');});
    $dbh->do(q{INSERT INTO public.dict_color_tags (name, color, border_color) VALUES ('желтый', 'f4e54d', 'd3c53b');});
    $dbh->do(q{INSERT INTO public.dict_color_tags (name, color, border_color) VALUES ('зеленый', 'b4e042', 'a5bd59');});
    $dbh->do(q{INSERT INTO public.dict_color_tags (name, color, border_color) VALUES ('голубой', '83c9fc', '6ea1bc');});
    $dbh->do(q{INSERT INTO public.dict_color_tags (name, color, border_color) VALUES ('лиловый', 'e4a6fc', 'd770f9');});
    $dbh->do(q{INSERT INTO public.dict_color_tags (name, color, border_color) VALUES ('серый', 'c8c8c8', 'a5a5a5');});


    $dbh->do(q{
CREATE TABLE public.color_tags (
    id SERIAL,
    realty_id int4 NOT NULL,
    user_id int4 NOT NULL,
    color_tag_id int4);
    });

    $dbh->do(q{ALTER TABLE public.color_tags ADD PRIMARY KEY (id);});

    $dbh->do(q{ALTER TABLE public.color_tags ADD CONSTRAINT color_tag_fk FOREIGN KEY (realty_id) REFERENCES public.realty (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;});
}

# Update models
system("$FindBin::Bin/../script/make_models");

exit 0;
