#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../lib";

use Rplus::Modern;

use Rplus::DB;

my $dbh = Rplus::DB->new_or_cached->dbh;

if (1) {

    # Update model
    $dbh->do(q{ALTER TABLE public.mediators ADD COLUMN last_seen_date TIMESTAMPTZ NOT NULL DEFAULT NOW();});

}

exit 1;
