#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../lib";

use Rplus::Modern;

use Rplus::DB;

my $dbh = Rplus::DB->new_or_cached->dbh;

if (1) {

    # Update model
    $dbh->do(q{ALTER TABLE public.users ADD COLUMN offer_mode VARCHAR NOT NULL DEFAULT 'sale';});
    $dbh->do(q{COMMENT ON COLUMN public.users.offer_mode IS 'режим, выбранный пользователем (аренда/продажа)';});
}

exit 1;
