#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../lib";

use Rplus::Modern;

use Rplus::Model::Realty;
use Rplus::Model::Realty::Manager;
use Rplus::Model::User;
use Rplus::Model::User::Manager;


use Data::Dumper;

say 'fixxxxing!';
say fix_acc_id() . ' object fixed';

sub fix_acc_id {
    my $count = 0;

    my $realty_iter = Rplus::Model::Realty::Manager->get_objects_iterator(query => ['!agent_id' => undef, account_id => undef,]);
    while (my $realty = $realty_iter->next) {
        if ($realty->agent_id != 10000) {
            my $user = Rplus::Model::User::Manager->get_objects(query => [id => $realty->agent_id])->[0];
            $count ++;
            $realty->account_id($user->account_id);
            $realty->save(changes_only => 1);
        }
    }

    return $count;
}