#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../lib";

use Rplus::Modern;

use Rplus::Model::Account;
use Rplus::Model::Account::Manager;
use Rplus::Model::Option;
use Rplus::Model::Option::Manager;

use JSON;
use Data::Dumper;

say 'fixxxxing!';
say fix_options() . ' object fixed';

sub fix_options {
    my $count = 0;

    my $account_iter = Rplus::Model::Account::Manager->get_objects_iterator(query => []);
    while (my $account = $account_iter->next) {
    
        my $options = Rplus::Model::Option::Manager->get_objects(query => [account_id => $account->id])->[0];
        
        my $opt = from_json($options->options);
        if ($opt->{multylisting}->{'company-name'}) {
            say $opt->{multylisting}->{'company-name'};
            $account->company_name($opt->{multylisting}->{'company-name'});
            $account->save;
            $count ++;
        }
    }
    
    return $count;
}