#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib", "$FindBin::Bin/../../RplusServer", "$FindBin::Bin/../../RplusWeb/lib";

# Start commands for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('RplusMgmt');
