#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../lib";

use Rplus::Modern;

use Rplus::Model::RealtyType;
use Rplus::Model::RealtyType::Manager;
use Rplus::Model::Option;
use Rplus::Model::Option::Manager;

use Data::Dumper;
use JSON;

say 'updating options';
say update_options() . ' objects updated';

sub update_options {
    my $count = 0;

    my @offer_types = ('sale', 'rent');
    my @new_types = ();
    my $new_types_iter = Rplus::Model::RealtyType::Manager->get_objects_iterator(query => [category_code => 'commercial',]);
    while (my $new_type = $new_types_iter->next) {
        push @new_types, $new_type->code;
    }

    my $option_iter = Rplus::Model::Option::Manager->get_objects_iterator(query => []);
    while (my $options = $option_iter->next) {
        my $opt = from_json($options->{options});

        for (my $i = 0; $i < @offer_types; $i ++) {
            for (my $j = 0; $j < @new_types; $j ++) {
                $opt->{import}->{$offer_types[$i] . '-' . $new_types[$j]} = 'true';
            }
        }

        $options->options(encode_json($opt));
        $options->save;
        $count ++;
    }

    return $count;
}
