#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../lib";

use Rplus::Modern;

use Rplus::Model::Photo;
use Rplus::Model::Photo::Manager;

use Rplus::Util::Config;

say 'updating photos';
update_photos();

sub update_photos {
    my $config = Rplus::Util::Config::get_config();
    my $subdomain = $config->{'subdomain'};

    my $photo_iter = Rplus::Model::Photo::Manager->get_objects_iterator(query => [delete_date => undef]);
    while (my $p = $photo_iter->next) {
		my $file_name = $p->filename;
		my $thumb_file_name = $p->thumbnail_filename;
		
		if ($file_name =~ /^.+\/(\d+\.jpg)/) {
			$p->filename($1);
		}
		if ($thumb_file_name =~ /^.+\/(\d+\_thumbnail.jpg)/) {
			$p->thumbnail_filename($1);
		}		
		$p->save(changes_only => 1);
    }
}