#!/usr/bin/env perl

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

use Rplus::Modern;

use Rplus::Model::Account;
use Rplus::Model::Account::Manager;
use Rplus::Model::Realty;
use Rplus::Model::Realty::Manager;

use Mojo::UserAgent;
use JSON;

my $ua = Mojo::UserAgent->new;

my $account_iter = Rplus::Model::Account::Manager->get_objects_iterator(query => [del_date => undef]);
while (my $account = $account_iter->next) {
    
    my $acc_data;
    my $tx = $ua->get('http://rplusmgmt.com/api/account/get_by_name?name=' . $account->name);
    if (my $res = $tx->success) {
        if ($res->json->{'status'} eq 'ok') {
            $acc_data = $res->json->{'data'};
            if ($acc_data->{balance} < 0) {
                say $account->name;
                say $acc_data->{balance};
                
                my $num_rows_updated = Rplus::Model::Realty::Manager->update_objects(
                    set => {multylisting => 0},
                    where => [account_id => $account->id],
                );
                say $num_rows_updated  . "\n";
            }
        }
    }
}

sub disable_mls {

}
