#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../../lib";

use Rplus::Modern;

use Rplus::Model::Realty;
use Rplus::Model::Realty::Manager;
use Rplus::Model::Mediator;
use Rplus::Model::Mediator::Manager;
use Rplus::Model::RuntimeParam;
use Rplus::Model::RuntimeParam::Manager;

use Rplus::Util::Image;
use Rplus::Util::Realty;

use Mojo::UserAgent;

use JSON;


run(Rplus::Util::Config::get_config());

sub run {
    my $config = shift;

    sleep int(rand(10));
    while(get_load_average() > 6) {
        say 'go to sleep';
        sleep int(rand(60));
    }

    # Загрузим базу телефонов посредников
    my %MEDIATOR_PHONES;
    {
        my $mediator_iter = Rplus::Model::Mediator::Manager->get_objects_iterator(query => [delete_date => undef], require_objects => ['company']);
        while (my $x = $mediator_iter->next) {
            $MEDIATOR_PHONES{$x->phone_num} = {
                id => $x->id,
                name => $x->name,
                company => $x->company->name,
            };
        }
    }

    my $ua = Mojo::UserAgent->new;    
    
    my $rt_param = Rplus::Model::RuntimeParam->new(key => 'import_param')->load();
    my $last_ts;
    if (!$rt_param) {
        $rt_param = Rplus::Model::RuntimeParam->new(key => 'import_param', ts => 'now()')->save; # Create record
    } 
    $last_ts = $rt_param->ts;

    #my $rt_param = Rplus::Model::RuntimeParam->new(key => 'opt_var')->load();
    
    my $import_param = Rplus::Model::RuntimeParam->new(key => 'opt_var')->load();
    my $import_obj = from_json($import_param->{value});

    while (my ($key, $value) = each $import_obj) {
        my @t = split '-', $key;
        my $offer_type = $t[0];
        my $source_media = $t[1];
        my $realty_type = $t[2];

        next if $value eq '0';

        say $source_media . ' - ' . $realty_type;

        while(get_load_average() > 6) {
            say 'go to sleep';
            sleep int(rand(30));
        }

        my $tx = $ua->get("http://192.168.5.1:3000/api/realty/list", form => {last_ts => $last_ts, offer_type => $offer_type, source_media => $source_media, realty_type => $realty_type});
        if (my $res = $tx->success) {
            my $realty_data = $res->json->{list};
NEXT:       for my $data (@$realty_data) {

                while(get_load_average() > 6) {
                    print 'go to sleep';
                    sleep int(rand(10));
                }

                for (@{$data->{'owner_phones'}}) {
                    if(exists $MEDIATOR_PHONES{$_}) {
                        if ($data->{offer_type_code} eq 'rent') {
                          next NEXT;
                        }
                        my $mediator = Rplus::Model::Mediator::Manager->get_objects(query => [phone_num => $_, delete_date => undef], require_objects => ['company'])->[0];
                        $data->{agent_id} = 10000;
                        last;
                    }
                }

                my $id;
                if ($id = Rplus::Util::Realty->find_similar(%$data, state_code => ['raw', 'work', 'suspended'])) {
                    say "Found similar realty: $id";
                    my $data_id = $data->{id};
                    my $o_realty = Rplus::Model::Realty->new(id => $id)->load;
                    $o_realty->source_media_id($data->{source_media_id});
                    $o_realty->source_media_text($data->{source_media_text});
                    $o_realty->last_seen_date($data->{add_date});
                    $o_realty->owner_price($data->{owner_price});
                    $o_realty->save(changes_only => 1);
                    say "updated realty: $id";

                    Rplus::Util::Image::remove_images($id);
                    my $tx = $ua->get("http://192.168.5.1:3000/api/realty/get_photos?realty_id=$data_id");
                    if (my $res = $tx->success) {
                        my $photo_data = $res->json->{list};
                        for my $photo (@$photo_data) {

                            my $new_photo = Rplus::Model::Photo->new;
                            # Save
                            $new_photo->realty_id($id);
                            $new_photo->filename($photo->{photo_url});
                            $new_photo->thumbnail_filename($photo->{thumbnail_url});

                            $new_photo->save;
                        }
                    }
                } else {
                    eval {
                        my $realty = Rplus::Model::Realty->new((map { $_ => $data->{$_} } grep { $_ ne 'category_code' && $_ ne 'id' } keys %$data), state_code => 'raw');
                        $realty->save;
                        my $data_id = $data->{id};
                        my $id = $realty->id;
                        say "Saved new realty: $id";
                        
                        my $tx = $ua->get("http://192.168.5.1:3000/api/realty/get_photos?realty_id=$data_id");
                        if (my $res = $tx->success) {
                            my $photo_data = $res->json->{list};
                            for my $photo (@$photo_data) {

                                my $new_photo = Rplus::Model::Photo->new;
                                # Save
                                $new_photo->realty_id($id);
                                $new_photo->filename($photo->{photo_url});
                                $new_photo->thumbnail_filename($photo->{thumbnail_url});

                                $new_photo->save;
                            }
                        }

                        # Сохраним историю
                        if ($id && !Rplus::Model::MediaImportHistory::Manager->get_objects_count(query => [media_id => $data->{source_media_id}, media_num => '', realty_id => $id])) {
                            Rplus::Model::MediaImportHistory->new(media_id => $data->{source_media_id}, media_num => '', media_text => $data->{'source_media_text'}, realty_id => $id)->save;                    
                        }
                    } or do {
                        say $@;
                    };
                }
            }
        }
    }
    $rt_param->ts('now');
    $rt_param->save(chages_only => 1);
}

sub get_load_average {
    open(LOAD, "/proc/loadavg") or die "Unable to get server load \n";
    my $load_avg = <LOAD>;
    close LOAD;
    my ( $one_min_avg ) = split /\s/, $load_avg;
    return $one_min_avg;
}

1;
